CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(20) UNIQUE NOT NULL,
  "age" int NOT NULL,
  "id_roles" int NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "video_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) UNIQUE NOT NULL,
  "url" varchar(35) UNIQUE NOT NULL
);

CREATE TABLE "course_general" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) UNIQUE NOT NULL,
  "description" varchar(50) UNIQUE NOT NULL,
  "id_level" int NOT NULL,
  "id_teacher" int NOT NULL,
  "id_user" int NOT NULL,
  "id_categories" int NOT NULL,
  "id_videos" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_roles") REFERENCES "roles" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_videos") REFERENCES "video_course" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_level") REFERENCES "level" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

/*Insert Roles*/

ntrega1=# INSERT INTO roles (name) VALUES ('Student');
entrega1=# INSERT INTO roles (name) VALUES ('Teacher');
entrega1=# INSERT INTO roles (name) VALUES ('Admin');
entrega1=# SELECT * FROM roles;


/*Insert Users*/
entrega1=# INSERT INTO users (name,email,password,age,id_roles) VALUES ('Andree','Andree@gmail.com','andree123',19,1),('Rosa','rosa@gmail.com','rosa123',21,1),('Juan','juan@gmail.com','juan123',35,2),('Arturo','arturo@gmail.com','arturo123',65,3);

entrega1=# SELECT * FROM users;


entrega1=#
/*Insert Categories*/

entrega1=# INSERT INTO categories (name) VALUES ('Diseño UIX'),('Programacion'),('Seguridad');
entrega1=# SELECT * FROM categories;

/*Insert Teacher*/

entrega1=# INSERT INTO teacher (name) VALUES ('Brenda'),('Iam'),('Andres');
entrega1=# SELECT * FROM teacher;

/*Insert Video_Course*/

entrega1=# INSERT INTO video_course (title,url) VALUES ('CSS','https://css.com'),('JavaScript','https://javascript.com'),('HTML','https://html.com'),('Ruby','https//ruby.com'),('React','https://react.com'),('Cybersecurity','https://cybersecurity');

entrega1=# SELECT * FROM video_course;
/*Insert Course_General*/

entrega1=#  INSERT INTO course_general (title,description,id_level,id_teacher,id_user,id_categories,id_videos) VALUES ('JavaScript','Tecnologias para controlar funcionalidades',3,2,2,2,2),('HTML','Maquetado Pagina web',2,3,1,2,3),('Ruby','Fundamentos Baiscos',1,1,2,1,4),('React','Redux, Reducer y Hooks',2,2,2,1,5),('Cybersecurity','Seguridad AWS',3,3,1,3,6);

entrega1=# SELECT * FROM course_general;

/*GENERAL-TABLE*/
entrega1=# SELECT course_general.id , course_general.title, course_general.description , level.name , users.name , categories.name, video_course.title, video_course.url, teacher.name FROM course_general JOIN level ON level.id=course_general.id_level JOIN users ON users.id=course_general.id_user JOIN categories ON categories.id=course_general.id_categories JOIN video_course ON video_course.id=course_general.id_videos JOIN teacher ON teacher.id=course_general.id_teacher;

entrega1=#